import { environment } from 'src/environments/environment';

const bootstrapUrl = `${environment.baseUrl}api/bootstrap`;
const baselineUrl = `${environment.baseUrl}api/baseline`;

export const hardcoded = {
  [bootstrapUrl]: {
    columnNames: [
      'id',
      'credits_this_bank',
      'present_res_since',
      'duration_in_month',
      'people_under_maintenance',
      'installment_as_income_perc',
      'age',
      'credit_amount',
      'account_check_status_0 <= ... < 200 DM',
      'account_check_status_< 0 DM',
      'account_check_status_>= 200 DM / salary assignments for at least 1 year',
      'account_check_status_no checking account',
      'credit_history_all credits at this bank paid back duly',
      'credit_history_critical account/ other credits existing (not at this bank)',
      'credit_history_delay in paying off in the past',
      'credit_history_existing credits paid back duly till now',
      'credit_history_no credits taken/ all credits paid back duly',
      'purpose_(vacation - does not exist?)',
      'purpose_business',
      'purpose_car (new)',
      'purpose_car (used)',
      'purpose_domestic appliances',
      'purpose_education',
      'purpose_furniture/equipment',
      'purpose_radio/television',
      'purpose_repairs',
      'purpose_retraining',
      'savings_.. >= 1000 DM ',
      'savings_... < 100 DM',
      'savings_100 <= ... < 500 DM',
      'savings_500 <= ... < 1000 DM ',
      'savings_unknown/ no savings account',
      'present_emp_since_.. >= 7 years',
      'present_emp_since_... < 1 year ',
      'present_emp_since_1 <= ... < 4 years',
      'present_emp_since_4 <= ... < 7 years',
      'present_emp_since_unemployed',
      'gender_female ',
      'gender_male ',
      'personal_status_ divorced/separated',
      'personal_status_ divorced/separated/married',
      'personal_status_ married/widowed',
      'personal_status_ single',
      'property_if not A121 : building society savings agreement/ life insurance',
      'property_if not A121/A122 : car or other, not in attribute 6',
      'property_real estate',
      'property_unknown / no property',
      'other_installment_plans_bank',
      'other_installment_plans_none',
      'other_installment_plans_stores',
      'housing_for free',
      'housing_own',
      'housing_rent',
      'job_management/ self-employed/ highly qualified employee/ officer',
      'job_skilled employee / official',
      'job_unemployed/ unskilled - non-resident',
      'job_unskilled - resident',
      'telephone_none',
      'telephone_yes, registered under the customers name ',
      'other_debtors_co-applicant',
      'other_debtors_guarantor',
      'other_debtors_none',
      'foreign_worker_no',
      'foreign_worker_yes',
      'young',
      'adult',
      'senior',
    ],
    fairnessDifficulties: [],
    fairnessItems: [],
    overview: [
      {
        aggregates: [
          { name: 'mean', value: 0.7377631001670736 },
          { name: 'median', value: 0.7404371584699454 },
          { name: 'q05', value: 0.7060392267532102 },
          { name: 'q95', value: 0.7713429029437482 },
          { name: 'std', value: 0.019970595495275585 },
          { name: 'mad', value: 0.015927337648719925 },
        ],
        histogram: [
          { frequency: 5, interval: 0.6925207756232687 },
          { frequency: 5, interval: 0.7018209768813172 },
          { frequency: 11, interval: 0.7111211781393657 },
          { frequency: 11, interval: 0.7204213793974141 },
          { frequency: 14, interval: 0.7297215806554626 },
          { frequency: 25, interval: 0.739021781913511 },
          { frequency: 14, interval: 0.7483219831715595 },
          { frequency: 8, interval: 0.7576221844296079 },
          { frequency: 4, interval: 0.7669223856876564 },
          { frequency: 3, interval: 0.7762225869457049 },
        ],
        key: 'Accuracy',
        name: 'Accuracy',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.6308993239979265 },
          { name: 'median', value: 0.6339743589743589 },
          { name: 'q05', value: 0.5285064935064935 },
          { name: 'q95', value: 0.7296456086286593 },
          { name: 'std', value: 0.06323308021133764 },
          { name: 'mad', value: 0.0494883101751408 },
        ],
        histogram: [
          { frequency: 2, interval: 0.4666666666666667 },
          { frequency: 5, interval: 0.5042105263157894 },
          { frequency: 13, interval: 0.5417543859649123 },
          { frequency: 20, interval: 0.5792982456140351 },
          { frequency: 20, interval: 0.6168421052631579 },
          { frequency: 27, interval: 0.6543859649122807 },
          { frequency: 8, interval: 0.6919298245614035 },
          { frequency: 4, interval: 0.7294736842105263 },
          { frequency: 0, interval: 0.7670175438596492 },
          { frequency: 1, interval: 0.8045614035087719 },
        ],
        key: 'Precision',
        name: 'Precision',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.3343856475416551 },
          { name: 'median', value: 0.3285991531404375 },
          { name: 'q05', value: 0.25599712540424 },
          { name: 'q95', value: 0.4273376623376623 },
          { name: 'std', value: 0.05223528401513105 },
          { name: 'mad', value: 0.04226803178119518 },
        ],
        histogram: [
          { frequency: 3, interval: 0.21666666666666667 },
          { frequency: 7, interval: 0.24065217391304347 },
          { frequency: 10, interval: 0.26463768115942027 },
          { frequency: 12, interval: 0.2886231884057971 },
          { frequency: 24, interval: 0.3126086956521739 },
          { frequency: 13, interval: 0.3365942028985507 },
          { frequency: 11, interval: 0.3605797101449275 },
          { frequency: 9, interval: 0.38456521739130434 },
          { frequency: 8, interval: 0.40855072463768116 },
          { frequency: 3, interval: 0.43253623188405793 },
        ],
        key: 'Recall',
        name: 'Recall',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.7518199115757751 },
          { name: 'median', value: 0.7510234243437189 },
          { name: 'q05', value: 0.7214515843375412 },
          { name: 'q95', value: 0.7817549214716005 },
          { name: 'std', value: 0.020189370531261294 },
          { name: 'mad', value: 0.016873860093490952 },
        ],
        histogram: [
          { frequency: 2, interval: 0.6995283018867924 },
          { frequency: 2, interval: 0.7096489029397687 },
          { frequency: 8, interval: 0.719769503992745 },
          { frequency: 21, interval: 0.7298901050457213 },
          { frequency: 15, interval: 0.7400107060986976 },
          { frequency: 14, interval: 0.7501313071516739 },
          { frequency: 21, interval: 0.7602519082046502 },
          { frequency: 11, interval: 0.7703725092576265 },
          { frequency: 3, interval: 0.7804931103106028 },
          { frequency: 3, interval: 0.790613711363579 },
        ],
        key: 'AUC',
        name: 'AUC',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.43387893627971275 },
          { name: 'median', value: 0.43373493975903615 },
          { name: 'q05', value: 0.35769921436588104 },
          { name: 'q95', value: 0.510109756097561 },
          { name: 'std', value: 0.047792896240471096 },
          { name: 'mad', value: 0.03838642937677095 },
        ],
        histogram: [
          { frequency: 5, interval: 0.3312101910828026 },
          { frequency: 8, interval: 0.3524369980614789 },
          { frequency: 10, interval: 0.3736638050401551 },
          { frequency: 11, interval: 0.3948906120188314 },
          { frequency: 19, interval: 0.41611741899750765 },
          { frequency: 16, interval: 0.43734422597618394 },
          { frequency: 13, interval: 0.45857103295486024 },
          { frequency: 7, interval: 0.47979783993353653 },
          { frequency: 10, interval: 0.5010246469122128 },
          { frequency: 1, interval: 0.522251453890889 },
        ],
        key: 'F1-Score',
        name: 'F1-Score',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.17641999729028085 },
          { name: 'median', value: 0.17554968126189058 },
          { name: 'q05', value: 0.16233828593966446 },
          { name: 'q95', value: 0.19132381584031863 },
          { name: 'std', value: 0.00871909251811408 },
          { name: 'mad', value: 0.007011921732595949 },
        ],
        histogram: [
          { frequency: 3, interval: 0.15633378016085792 },
          { frequency: 8, interval: 0.16025164868216824 },
          { frequency: 5, interval: 0.16416951720347858 },
          { frequency: 18, interval: 0.1680873857247889 },
          { frequency: 17, interval: 0.17200525424609925 },
          { frequency: 16, interval: 0.17592312276740957 },
          { frequency: 9, interval: 0.1798409912887199 },
          { frequency: 12, interval: 0.18375885981003023 },
          { frequency: 7, interval: 0.18767672833134055 },
          { frequency: 5, interval: 0.1915945968526509 },
        ],
        key: 'Brier',
        name: 'Brier',
        type: 'performance',
      },
    ],
    performanceDifficulties: [
      { name: 949, value: 0.9671875 },
      { name: 331, value: 0.94625 },
      { name: 963, value: 0.9157142857142857 },
      { name: 228, value: 0.9071428571428571 },
      { name: 861, value: 0.8954545454545455 },
      { name: 757, value: 0.8884615384615384 },
      { name: 435, value: 0.8878787878787879 },
      { name: 505, value: 0.8868421052631579 },
      { name: 278, value: 0.881578947368421 },
      { name: 978, value: 0.8742857142857143 },
    ],
    performanceItems: [
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.17312809797402615,
          },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.12195345339952564,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.1186753015455723,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.07897764922987008,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 1.0,
          age: 31.0,
          credit_amount: 3621.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 2.0,
          duration_in_month: 24.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 949,
          installment_as_income_perc: 2.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 1.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 4.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 1.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 1.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.95 },
          { name: 'positive', value: 0.05 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.16084595061543,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.12386381236996863,
          },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.12245687995204418,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=1',
            value: -0.08044832024357912,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 1.0,
          age: 30.0,
          credit_amount: 1864.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 1.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 2.0,
          duration_in_month: 18.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 1.0,
          'gender_male ': 0.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 331,
          installment_as_income_perc: 4.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 1.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 0.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 1.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 2.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 1.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 1.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 1.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.95 },
          { name: 'positive', value: 0.05 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.16681050259373528,
          },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.1274576210716395,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.1159555732640018,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.08282436847482076,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 1.0,
          age: 35.0,
          credit_amount: 2397.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 2.0,
          duration_in_month: 24.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 963,
          installment_as_income_perc: 3.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 1.0,
          other_installment_plans_none: 0.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 1.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 2.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 1.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 1.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 0.0,
          'telephone_yes, registered under the customers name ': 1.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.0 },
          { name: 'positive', value: 1.0 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.17418617538098657,
          },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.13329994153913238,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.11927575198739103,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.08143628309979224,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 0.0,
          age: 22.0,
          credit_amount: 1478.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 9.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 228,
          installment_as_income_perc: 4.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 1.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 2.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 1.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 1.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.85 },
          { name: 'positive', value: 0.15 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.15849043668989848,
          },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.12574757422778393,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.11478755118130758,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.07381721817086871,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 1.0,
          age: 28.0,
          credit_amount: 2169.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 1.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 18.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 861,
          installment_as_income_perc: 4.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 1.0,
          'personal_status_ single': 0.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 1.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 2.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 1.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 1.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 1.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 0.0,
          'telephone_yes, registered under the customers name ': 1.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.05 },
          { name: 'positive', value: 0.95 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.14884532577525983,
          },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.12707733671968627,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.11802767223957308,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=1',
            value: -0.07966064361255908,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 1.0,
          'account_check_status_no checking account': 0.0,
          adult: 0.0,
          age: 39.0,
          credit_amount: 1271.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 1.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 2.0,
          duration_in_month: 15.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 1.0,
          housing_own: 0.0,
          housing_rent: 0.0,
          id: 757,
          installment_as_income_perc: 3.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 1.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 4.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 1.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 1.0,
          senior: 1.0,
          telephone_none: 0.0,
          'telephone_yes, registered under the customers name ': 1.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.05 },
          { name: 'positive', value: 0.95 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.17979439346359632,
          },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.1261307910042199,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.11448947913345987,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.07829412569807723,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 1.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 0.0,
          age: 25.0,
          credit_amount: 1484.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 12.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 435,
          installment_as_income_perc: 2.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 1.0,
          'personal_status_ single': 0.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 1.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 1.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 1.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 1.0,
          senior: 0.0,
          telephone_none: 0.0,
          'telephone_yes, registered under the customers name ': 1.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.35 },
          { name: 'positive', value: 0.65 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.16914183900588567,
          },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.12774175386845288,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.11708046610406356,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.0858755485064265,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 0.0,
          age: 27.0,
          credit_amount: 1309.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 10.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 505,
          installment_as_income_perc: 4.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 0.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 1.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 1.0,
          other_debtors_none: 0.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 1.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 4.0,
          'property_if not A121 : building society savings agreement/ life insurance': 1.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 1.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 1.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.8 },
          { name: 'positive', value: 0.2 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.18065505032122647,
          },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.1267001682786814,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.12426742771240187,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.08544791566323608,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 1.0,
          age: 32.0,
          credit_amount: 4611.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 6.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 1.0,
          'gender_male ': 0.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 278,
          installment_as_income_perc: 1.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 1.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 0.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 1.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 4.0,
          'property_if not A121 : building society savings agreement/ life insurance': 1.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 1.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 1.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 1.0 },
          { name: 'positive', value: 0.0 },
        ],
      },
      {
        explanation: [
          {
            name:
              'credit_history_no credits taken/ all credits paid back duly=0',
            value: -0.160885882038628,
          },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.1262370905509523,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.1203656537327106,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.08639642863572193,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 0.0,
          age: 47.0,
          credit_amount: 2538.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 1.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 2.0,
          duration_in_month: 24.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 978,
          installment_as_income_perc: 4.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 0.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 1.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 2.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 1.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 4.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 1.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 1.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 1.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 1.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.5 },
          { name: 'positive', value: 0.5 },
        ],
      },
    ],
  },
  [baselineUrl]: {
    columnNames: [
      'id',
      'credits_this_bank',
      'present_res_since',
      'duration_in_month',
      'people_under_maintenance',
      'installment_as_income_perc',
      'age',
      'credit_amount',
      'account_check_status_0 <= ... < 200 DM',
      'account_check_status_< 0 DM',
      'account_check_status_>= 200 DM / salary assignments for at least 1 year',
      'account_check_status_no checking account',
      'credit_history_all credits at this bank paid back duly',
      'credit_history_critical account/ other credits existing (not at this bank)',
      'credit_history_delay in paying off in the past',
      'credit_history_existing credits paid back duly till now',
      'credit_history_no credits taken/ all credits paid back duly',
      'purpose_(vacation - does not exist?)',
      'purpose_business',
      'purpose_car (new)',
      'purpose_car (used)',
      'purpose_domestic appliances',
      'purpose_education',
      'purpose_furniture/equipment',
      'purpose_radio/television',
      'purpose_repairs',
      'purpose_retraining',
      'savings_.. >= 1000 DM ',
      'savings_... < 100 DM',
      'savings_100 <= ... < 500 DM',
      'savings_500 <= ... < 1000 DM ',
      'savings_unknown/ no savings account',
      'present_emp_since_.. >= 7 years',
      'present_emp_since_... < 1 year ',
      'present_emp_since_1 <= ... < 4 years',
      'present_emp_since_4 <= ... < 7 years',
      'present_emp_since_unemployed',
      'gender_female ',
      'gender_male ',
      'personal_status_ divorced/separated',
      'personal_status_ divorced/separated/married',
      'personal_status_ married/widowed',
      'personal_status_ single',
      'property_if not A121 : building society savings agreement/ life insurance',
      'property_if not A121/A122 : car or other, not in attribute 6',
      'property_real estate',
      'property_unknown / no property',
      'other_installment_plans_bank',
      'other_installment_plans_none',
      'other_installment_plans_stores',
      'housing_for free',
      'housing_own',
      'housing_rent',
      'job_management/ self-employed/ highly qualified employee/ officer',
      'job_skilled employee / official',
      'job_unemployed/ unskilled - non-resident',
      'job_unskilled - resident',
      'telephone_none',
      'telephone_yes, registered under the customers name ',
      'other_debtors_co-applicant',
      'other_debtors_guarantor',
      'other_debtors_none',
      'foreign_worker_no',
      'foreign_worker_yes',
      'young',
      'adult',
      'senior',
    ],
    fairnessDifficulties: [],
    fairnessItems: [],
    overview: [
      {
        aggregates: [
          { name: 'mean', value: 0.661861259912746 },
          { name: 'median', value: 0.6617443570007784 },
          { name: 'q05', value: 0.6254981028142809 },
          { name: 'q95', value: 0.6947094244503571 },
          { name: 'std', value: 0.02288835602100008 },
          { name: 'mad', value: 0.017819168596955138 },
        ],
        histogram: [
          { frequency: 1, interval: 0.5830985915492958 },
          { frequency: 2, interval: 0.5957993706922385 },
          { frequency: 1, interval: 0.6085001498351813 },
          { frequency: 5, interval: 0.6212009289781241 },
          { frequency: 12, interval: 0.6339017081210668 },
          { frequency: 25, interval: 0.6466024872640096 },
          { frequency: 23, interval: 0.6593032664069524 },
          { frequency: 12, interval: 0.6720040455498951 },
          { frequency: 15, interval: 0.6847048246928379 },
          { frequency: 4, interval: 0.6974056038357807 },
        ],
        key: 'Accuracy',
        name: 'Baseline Accuracy',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.4545442311872659 },
          { name: 'median', value: 0.45806451612903226 },
          { name: 'q05', value: 0.38863427415647694 },
          { name: 'q95', value: 0.52 },
          { name: 'std', value: 0.03919643823109604 },
          { name: 'mad', value: 0.030654893848889798 },
        ],
        histogram: [
          { frequency: 3, interval: 0.34838709677419355 },
          { frequency: 2, interval: 0.3668817204301075 },
          { frequency: 6, interval: 0.3853763440860215 },
          { frequency: 7, interval: 0.4038709677419355 },
          { frequency: 16, interval: 0.42236559139784946 },
          { frequency: 20, interval: 0.44086021505376344 },
          { frequency: 19, interval: 0.4593548387096774 },
          { frequency: 13, interval: 0.4778494623655914 },
          { frequency: 7, interval: 0.49634408602150537 },
          { frequency: 7, interval: 0.5148387096774194 },
        ],
        key: 'Precision',
        name: 'Baseline Precision',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.6306673916303529 },
          { name: 'median', value: 0.6339743589743589 },
          { name: 'q05', value: 0.5345262966663639 },
          { name: 'q95', value: 0.7080574956979451 },
          { name: 'std', value: 0.04937761880242464 },
          { name: 'mad', value: 0.03876915644786645 },
        ],
        histogram: [
          { frequency: 3, interval: 0.5 },
          { frequency: 4, interval: 0.5256521739130435 },
          { frequency: 4, interval: 0.551304347826087 },
          { frequency: 17, interval: 0.5769565217391304 },
          { frequency: 17, interval: 0.6026086956521739 },
          { frequency: 24, interval: 0.6282608695652174 },
          { frequency: 15, interval: 0.6539130434782608 },
          { frequency: 10, interval: 0.6795652173913043 },
          { frequency: 5, interval: 0.7052173913043478 },
          { frequency: 1, interval: 0.7308695652173913 },
        ],
        key: 'Recall',
        name: 'Baseline Recall',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.7166757006339008 },
          { name: 'median', value: 0.7186420743606978 },
          { name: 'q05', value: 0.6682742219488913 },
          { name: 'q95', value: 0.7570631799972181 },
          { name: 'std', value: 0.028706753052986284 },
          { name: 'mad', value: 0.022645465377531267 },
        ],
        histogram: [
          { frequency: 1, interval: 0.6161222421454744 },
          { frequency: 1, interval: 0.6318384621425561 },
          { frequency: 3, interval: 0.6475546821396377 },
          { frequency: 6, interval: 0.6632709021367195 },
          { frequency: 7, interval: 0.6789871221338011 },
          { frequency: 22, interval: 0.6947033421308828 },
          { frequency: 18, interval: 0.7104195621279645 },
          { frequency: 23, interval: 0.7261357821250461 },
          { frequency: 14, interval: 0.7418520021221279 },
          { frequency: 5, interval: 0.7575682221192095 },
        ],
        key: 'AUC',
        name: 'Baseline AUC',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.5274043706422471 },
          { name: 'median', value: 0.5316142412720359 },
          { name: 'q05', value: 0.4497898571028298 },
          { name: 'q95', value: 0.5803411327356222 },
          { name: 'std', value: 0.03809595113092009 },
          { name: 'mad', value: 0.028790613416614253 },
        ],
        histogram: [
          { frequency: 4, interval: 0.421875 },
          { frequency: 3, interval: 0.4418303571428571 },
          { frequency: 2, interval: 0.4617857142857143 },
          { frequency: 10, interval: 0.4817410714285714 },
          { frequency: 21, interval: 0.5016964285714286 },
          { frequency: 24, interval: 0.5216517857142857 },
          { frequency: 20, interval: 0.5416071428571428 },
          { frequency: 11, interval: 0.5615625 },
          { frequency: 2, interval: 0.5815178571428572 },
          { frequency: 3, interval: 0.6014732142857143 },
        ],
        key: 'F1-Score',
        name: 'Baseline F1-Score',
        type: 'performance',
      },
      {
        aggregates: [
          { name: 'mean', value: 0.21874121976874933 },
          { name: 'median', value: 0.21828084388097907 },
          { name: 'q05', value: 0.2117563390593062 },
          { name: 'q95', value: 0.2261708211060691 },
          { name: 'std', value: 0.005672492379735555 },
          { name: 'mad', value: 0.004218642460043076 },
        ],
        histogram: [
          { frequency: 5, interval: 0.20814874013223078 },
          { frequency: 21, interval: 0.21170129576050298 },
          { frequency: 26, interval: 0.21525385138877515 },
          { frequency: 24, interval: 0.21880640701704734 },
          { frequency: 18, interval: 0.2223589626453195 },
          { frequency: 2, interval: 0.2259115182735917 },
          { frequency: 2, interval: 0.2294640739018639 },
          { frequency: 0, interval: 0.23301662953013608 },
          { frequency: 1, interval: 0.23656918515840827 },
          { frequency: 1, interval: 0.24012174078668044 },
        ],
        key: 'Brier',
        name: 'Baseline Brier',
        type: 'performance',
      },
    ],
    performanceDifficulties: [
      { name: 616, value: 0.8222256080537362 },
      { name: 637, value: 0.8175634552845487 },
      { name: 134, value: 0.7930688485388984 },
      { name: 272, value: 0.7776697699512165 },
      { name: 255, value: 0.7724145963865001 },
      { name: 137, value: 0.771479004908768 },
      { name: 285, value: 0.7579096716891511 },
      { name: 130, value: 0.7542083866213206 },
      { name: 286, value: 0.7533300229809943 },
      { name: 945, value: 0.7519226078976884 },
    ],
    performanceItems: [
      {
        explanation: [
          { name: 'duration_in_month=60', value: 0.2585513603372054 },
          { name: 'age <= 27.00', value: 0.10084260808543359 },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.037300135271745846,
          },
          {
            name: 'installment_as_income_perc=2',
            value: -0.02661441900496174,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 1.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 0.0,
          age: 27.0,
          credit_amount: 9157.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 1.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 60.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 1.0,
          housing_own: 0.0,
          housing_rent: 0.0,
          id: 616,
          installment_as_income_perc: 2.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 1.0,
          'job_skilled employee / official': 0.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 1.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 2.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 1.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 1.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.1564738826518728 },
          { name: 'positive', value: 0.8435261173481272 },
        ],
      },
      {
        explanation: [
          { name: 'duration_in_month=60', value: 0.26041043805797964 },
          { name: 'age <= 27.00', value: 0.09921214747418713 },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.03791341031334378,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.027518235347312788,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 0.0,
          age: 21.0,
          credit_amount: 15653.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 1.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 2.0,
          duration_in_month: 60.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 637,
          installment_as_income_perc: 2.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 1.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 4.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 1.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 1.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 0.0,
          'telephone_yes, registered under the customers name ': 1.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.16991814109144043 },
          { name: 'positive', value: 0.8300818589085596 },
        ],
      },
      {
        explanation: [
          { name: 'duration_in_month=60', value: 0.25677765843376504 },
          { name: 'age <= 27.00', value: 0.0920493464627755 },
          {
            name: 'account_check_status_no checking account=1',
            value: -0.037104615029309576,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.029272968779836758,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 1.0,
          adult: 0.0,
          age: 21.0,
          credit_amount: 10144.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 60.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 1.0,
          'gender_male ': 0.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 134,
          installment_as_income_perc: 2.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 1.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 0.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 1.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 4.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 1.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 1.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 0.0,
          'telephone_yes, registered under the customers name ': 1.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.19654723224036252 },
          { name: 'positive', value: 0.8034527677596375 },
        ],
      },
      {
        explanation: [
          { name: 'duration_in_month=48', value: 0.21846144262343203 },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.043890558634277134,
          },
          {
            name: 'installment_as_income_perc=4',
            value: 0.03961010429151716,
          },
          {
            name: 'account_check_status_< 0 DM=0',
            value: -0.021743985198810118,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 1.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 1.0,
          age: 36.0,
          credit_amount: 12169.0,
          'credit_history_all credits at this bank paid back duly': 1.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 48.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 1.0,
          housing_own: 0.0,
          housing_rent: 0.0,
          id: 272,
          installment_as_income_perc: 4.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 1.0,
          'job_skilled employee / official': 0.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 1.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 0.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 1.0,
          present_res_since: 4.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 1.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 1.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 1.0,
          senior: 0.0,
          telephone_none: 0.0,
          'telephone_yes, registered under the customers name ': 1.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.19994285375898735 },
          { name: 'positive', value: 0.8000571462410127 },
        ],
      },
      {
        explanation: [
          { name: 'duration_in_month=60', value: 0.264930703590526 },
          { name: 'age <= 27.00', value: 0.09478907850177266 },
          {
            name: 'installment_as_income_perc=1',
            value: -0.04595184404587596,
          },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.03690440627483427,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 1.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 0.0,
          age: 27.0,
          credit_amount: 7418.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 1.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 60.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 255,
          installment_as_income_perc: 1.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 0.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 1.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 1.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 1.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 1.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 1.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.20881627214378518 },
          { name: 'positive', value: 0.7911837278562148 },
        ],
      },
      {
        explanation: [
          { name: 'age > 42.00', value: -0.13785981810875175 },
          { name: 'duration_in_month=12', value: -0.07857353605368333 },
          {
            name: 'installment_as_income_perc=4',
            value: 0.04009776842927311,
          },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.03466530472504866,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 1.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 0.0,
          age: 66.0,
          credit_amount: 766.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 12.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 137,
          installment_as_income_perc: 4.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 0.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 1.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 1.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 3.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 1.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 1.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 1.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 1.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.7530695057492129 },
          { name: 'positive', value: 0.24693049425078709 },
        ],
      },
      {
        explanation: [
          {
            name: 'installment_as_income_perc=1',
            value: -0.048591101064723904,
          },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.034768553115251406,
          },
          {
            name: 'account_check_status_< 0 DM=1',
            value: 0.02567249220909408,
          },
          {
            name:
              'credit_history_critical account/ other credits existing (not at this bank)=0',
            value: 0.022874809977750578,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 1.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 1.0,
          age: 35.0,
          credit_amount: 10722.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 47.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 1.0,
          'gender_male ': 0.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 285,
          installment_as_income_perc: 1.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 0.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 1.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 1.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 0.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 1.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 1.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 1.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 1.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 1.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 0.0,
          'telephone_yes, registered under the customers name ': 1.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.23816199259756798 },
          { name: 'positive', value: 0.761838007402432 },
        ],
      },
      {
        explanation: [
          { name: 'duration_in_month=48', value: 0.204681543898814 },
          { name: 'age <= 27.00', value: 0.09756319212259185 },
          {
            name: 'installment_as_income_perc=1',
            value: -0.04780022585633102,
          },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.03463824173774391,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 1.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 0.0,
          age: 24.0,
          credit_amount: 8487.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 48.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 1.0,
          'gender_male ': 0.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 130,
          installment_as_income_perc: 1.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 1.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 0.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 1.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 2.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 1.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 1.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 1.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.24788608611041774 },
          { name: 'positive', value: 0.7521139138895823 },
        ],
      },
      {
        explanation: [
          { name: 'duration_in_month=48', value: 0.20030057496448597 },
          { name: 'age <= 27.00', value: 0.09445852955037894 },
          {
            name: 'installment_as_income_perc=4',
            value: 0.03827710776370743,
          },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.03716013288451325,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 0.0,
          'account_check_status_< 0 DM': 1.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 0.0,
          age: 26.0,
          credit_amount: 4788.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 1.0,
          'credit_history_no credits taken/ all credits paid back duly': 0.0,
          credits_this_bank: 1.0,
          duration_in_month: 48.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 0.0,
          'gender_male ': 1.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 286,
          installment_as_income_perc: 4.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 2.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 0.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 1.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 0.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 1.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 3.0,
          'property_if not A121 : building society savings agreement/ life insurance': 1.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 0.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 0.0,
          'purpose_car (used)': 1.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 1.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 0.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 1.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.23726227234859576 },
          { name: 'positive', value: 0.7627377276514042 },
        ],
      },
      {
        explanation: [
          { name: 'duration_in_month=48', value: 0.21143239042320197 },
          {
            name: 'installment_as_income_perc=1',
            value: -0.041176804715785484,
          },
          { name: '27.00 < age <= 33.00', value: 0.038211931823908495 },
          {
            name: 'account_check_status_no checking account=0',
            value: 0.03733130891698913,
          },
        ],
        instance: {
          'account_check_status_0 <= ... < 200 DM': 1.0,
          'account_check_status_< 0 DM': 0.0,
          'account_check_status_>= 200 DM / salary assignments for at least 1 year': 0.0,
          'account_check_status_no checking account': 0.0,
          adult: 1.0,
          age: 30.0,
          credit_amount: 8358.0,
          'credit_history_all credits at this bank paid back duly': 0.0,
          'credit_history_critical account/ other credits existing (not at this bank)': 0.0,
          'credit_history_delay in paying off in the past': 0.0,
          'credit_history_existing credits paid back duly till now': 0.0,
          'credit_history_no credits taken/ all credits paid back duly': 1.0,
          credits_this_bank: 2.0,
          duration_in_month: 48.0,
          foreign_worker_no: 0.0,
          foreign_worker_yes: 1.0,
          'gender_female ': 1.0,
          'gender_male ': 0.0,
          'housing_for free': 0.0,
          housing_own: 1.0,
          housing_rent: 0.0,
          id: 945,
          installment_as_income_perc: 1.0,
          'job_management/ self-employed/ highly qualified employee/ officer': 0.0,
          'job_skilled employee / official': 1.0,
          'job_unemployed/ unskilled - non-resident': 0.0,
          'job_unskilled - resident': 0.0,
          'other_debtors_co-applicant': 0.0,
          other_debtors_guarantor: 0.0,
          other_debtors_none: 1.0,
          other_installment_plans_bank: 0.0,
          other_installment_plans_none: 1.0,
          other_installment_plans_stores: 0.0,
          people_under_maintenance: 1.0,
          'personal_status_ divorced/separated': 0.0,
          'personal_status_ divorced/separated/married': 1.0,
          'personal_status_ married/widowed': 0.0,
          'personal_status_ single': 0.0,
          'present_emp_since_.. >= 7 years': 0.0,
          'present_emp_since_... < 1 year ': 1.0,
          'present_emp_since_1 <= ... < 4 years': 0.0,
          'present_emp_since_4 <= ... < 7 years': 0.0,
          present_emp_since_unemployed: 0.0,
          present_res_since: 1.0,
          'property_if not A121 : building society savings agreement/ life insurance': 0.0,
          'property_if not A121/A122 : car or other, not in attribute 6': 1.0,
          'property_real estate': 0.0,
          'property_unknown / no property': 0.0,
          'purpose_(vacation - does not exist?)': 0.0,
          purpose_business: 0.0,
          'purpose_car (new)': 1.0,
          'purpose_car (used)': 0.0,
          'purpose_domestic appliances': 0.0,
          purpose_education: 0.0,
          'purpose_furniture/equipment': 0.0,
          'purpose_radio/television': 0.0,
          purpose_repairs: 0.0,
          purpose_retraining: 0.0,
          'savings_.. >= 1000 DM ': 0.0,
          'savings_... < 100 DM': 0.0,
          'savings_100 <= ... < 500 DM': 0.0,
          'savings_500 <= ... < 1000 DM ': 1.0,
          'savings_unknown/ no savings account': 0.0,
          senior: 0.0,
          telephone_none: 1.0,
          'telephone_yes, registered under the customers name ': 0.0,
          young: 0.0,
        },
        predictProbablities: [
          { name: 'negative', value: 0.26709335792511335 },
          { name: 'positive', value: 0.7329066420748866 },
        ],
      },
    ],
  },
};
